disabled_rules: # rule identifiers to exclude from running
#  - colon
#  - comma
  - control_statement
  - trailing_whitespace
  - empty_count
  - trailing_newline
  - missing_docs
opt_in_rules: # some rules are only opt-in
  - missing_docs
  - cyclomatic_complexity
  
  # Find all the available rules by running:
  # swiftlint rules
whitelist_rules:
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 510
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
function_parameter_count:
  warning: 4
  error: 6
identifier_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
cyclomatic_complexity:
  warning: 5
  error: 7
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)